-- Time spent on tasks: adds the TaskTimeLog table.
--
-- One row per stretch of work logged against a task, so a task accumulates
-- many entries and its total time spent is the sum of them, rather than one
-- overwritten field. Keeps who logged what, and on which day.
--
--   minutes  whole minutes, so totals stay exact (no float rounding drift)
--   date     the day the work happened, not the day it was logged
--   note     optional free text
--
-- DDL generated by Prisma, not hand-written:
--   npx prisma migrate diff --from-schema-datamodel <pre-change schema> \
--       --to-schema-datamodel prisma/schema.prisma --script
--
-- Run against BOTH databases:
--   u230921990_office          (production, used by the live site)
--   u230921990_office_testing  (whatever local .env points at)
--
-- Nothing is dropped and no existing row is touched. Tasks with no logged
-- time simply show "Nothing logged".


-- ---------------------------------------------------------------------------
-- STEP 1 - preflight. Expect EMPTY. A row means step 2 is already applied.
-- ---------------------------------------------------------------------------
SHOW TABLES LIKE 'TaskTimeLog';


-- ---------------------------------------------------------------------------
-- STEP 2 - the migration.
-- ---------------------------------------------------------------------------
-- CREATE TABLE is guarded by IF NOT EXISTS and is safe to re-run. The foreign
-- keys are not: a second run fails with #1826 (duplicate foreign key), or
-- errno 121 on MariaDB. Either error is harmless and means it is already there.

-- CreateTable
CREATE TABLE IF NOT EXISTS `TaskTimeLog` (
    `id` VARCHAR(191) NOT NULL,
    `taskId` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `minutes` INTEGER NOT NULL,
    `date` DATETIME(3) NOT NULL,
    `note` TEXT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `TaskTimeLog_taskId_fkey`(`taskId`),
    INDEX `TaskTimeLog_userId_fkey`(`userId`),
    INDEX `TaskTimeLog_date_idx`(`date`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
-- CASCADE on both: deleting a task or a user removes their time entries, which
-- would otherwise point at rows that no longer exist.
ALTER TABLE `TaskTimeLog` ADD CONSTRAINT `TaskTimeLog_taskId_fkey` FOREIGN KEY (`taskId`) REFERENCES `Task`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `TaskTimeLog` ADD CONSTRAINT `TaskTimeLog_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;


-- ---------------------------------------------------------------------------
-- STEP 3 - verify. Uses SHOW rather than information_schema, which
-- shared-hosting users cannot read (MySQL error #1044).
-- ---------------------------------------------------------------------------
-- Expect all 8 columns and both CONSTRAINT lines, referencing Task and User.
SHOW CREATE TABLE `TaskTimeLog`;
