-- Per-service payment mapping for clients: adds the ClientService table.
--
-- One row per service a client is engaged for, carrying how that service is
-- billed. Payment type lives on the row, so a single client can be
-- percentage-based on Video Editing and package-based on Digital Marketing
-- at the same time.
--
--   paymentType   'Percentage' or 'Package'
--   percentage    set when Percentage. Percent, not a fraction: 20.00 = 20%
--   packageAmount set when Package. Amount in INR
--   billingCycle  set when Package: 'Monthly' or 'One-time'
--
-- DDL generated by Prisma, not hand-written:
--   npx prisma migrate diff --from-schema-datamodel <pre-change schema> \
--       --to-schema-datamodel prisma/schema.prisma --script
--
-- Run in phpMyAdmin (hPanel -> Databases -> Enter phpMyAdmin -> SQL tab)
-- against BOTH databases:
--   u230921990_office          (production, used by the live site)
--   u230921990_office_testing  (whatever local .env points at)
--
-- Nothing is dropped and no existing row is rewritten. The old
-- Client.services text column is left exactly as it is: it is no longer
-- written to, and is read only to pre-fill the edit form for clients created
-- before this change, so their services are not lost.
--
-- Requires the `Client` table to exist. Independent of
-- prisma/add-task-client-mapping.sql -- either order is fine.


-- ---------------------------------------------------------------------------
-- STEP 1 - preflight. Run this first and read the output.
-- ---------------------------------------------------------------------------
-- Expect one row named `Client`. If EMPTY, run prisma/create-missing-tables.sql
-- first: the foreign key below needs it and fails with #1215 without it.
SHOW TABLES LIKE 'Client';

-- Expect EMPTY. If it returns `ClientService`, step 2 is already applied here.
SHOW TABLES LIKE 'ClientService';


-- ---------------------------------------------------------------------------
-- STEP 2 - the migration.
-- ---------------------------------------------------------------------------
-- CREATE TABLE is guarded by IF NOT EXISTS and is safe to re-run, but the
-- foreign key is not: a second run fails with #1826 (duplicate foreign key).
-- That error is harmless and means this database already has it.

-- CreateTable
CREATE TABLE IF NOT EXISTS `ClientService` (
    `id` VARCHAR(191) NOT NULL,
    `clientId` VARCHAR(191) NOT NULL,
    `service` VARCHAR(191) NOT NULL,
    `focus` VARCHAR(191) NULL,
    `paymentType` VARCHAR(191) NOT NULL,
    `percentage` DECIMAL(5, 2) NULL,
    `packageAmount` DECIMAL(12, 2) NULL,
    `billingCycle` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `ClientService_clientId_fkey`(`clientId`),
    UNIQUE INDEX `ClientService_clientId_service_key`(`clientId`, `service`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
-- CASCADE on delete: removing a client removes its service/payment rows too.
ALTER TABLE `ClientService` ADD CONSTRAINT `ClientService_clientId_fkey` FOREIGN KEY (`clientId`) REFERENCES `Client`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;


-- ---------------------------------------------------------------------------
-- STEP 3 - verify. Uses SHOW rather than information_schema, which
-- shared-hosting users cannot read (MySQL error #1044).
-- ---------------------------------------------------------------------------
-- Expect all 10 columns, the UNIQUE key on (clientId, service), and the
-- CONSTRAINT `ClientService_clientId_fkey` REFERENCES `Client` (`id`).
SHOW CREATE TABLE `ClientService`;
