-- Per-count billing for Video Editing: adds ClientService.perUnitAmount.
--
-- Payment type is now restricted per service, in paymentTypesForService
-- (lib/services.ts):
--
--   Digital Marketing   'Percentage' or 'Package'   (unchanged)
--   Video Editing       'Per count'  or 'Package'   ('Per count' is new)
--   every other service 'Package' only
--
-- 'Per count' bills a rate for one delivered item, so it needs an amount
-- column of its own:
--
--   perUnitAmount  set when paymentType is 'Per count'. Rate in INR per item
--
-- DDL generated by Prisma, not hand-written:
--   npx prisma migrate diff --from-schema-datamodel <pre-change schema> \
--       --to-schema-datamodel prisma/schema.prisma --script
--
-- Only the AFTER clause is hand-added, so the new column sits beside
-- packageAmount in phpMyAdmin. It has no effect on behaviour.
--
-- Run in phpMyAdmin (hPanel -> Databases -> Enter phpMyAdmin -> SQL tab)
-- against BOTH databases:
--   u230921990_office          (production, used by the live site)
--   u230921990_office_testing  (whatever local .env points at)
--
-- Nothing is dropped and no existing row is rewritten. Rows written before
-- the restriction may still hold a percentage on a service that is now
-- package-only; they keep displaying as-is, and the edit form switches them
-- to the service's allowed type the next time that client is saved. Step 4
-- lists them so they can be re-entered deliberately.
--
-- Requires the `ClientService` table to exist
-- (prisma/add-client-service-payment.sql).


-- ---------------------------------------------------------------------------
-- STEP 1 - preflight. Run this first and read the output.
-- ---------------------------------------------------------------------------
-- Expect one row named `ClientService`. If EMPTY, run
-- prisma/add-client-service-payment.sql first.
SHOW TABLES LIKE 'ClientService';

-- Expect EMPTY. If it returns `perUnitAmount`, step 2 is already applied here.
SHOW COLUMNS FROM `ClientService` LIKE 'perUnitAmount';


-- ---------------------------------------------------------------------------
-- STEP 2 - the migration.
-- ---------------------------------------------------------------------------
-- Nullable with no default, so every existing row is untouched: only rows
-- saved as 'Per count' from here on will carry a value. A second run fails
-- with #1060 (duplicate column name), which is harmless and means this
-- database already has it.

-- AlterTable
ALTER TABLE `ClientService` ADD COLUMN `perUnitAmount` DECIMAL(12, 2) NULL AFTER `packageAmount`;


-- ---------------------------------------------------------------------------
-- STEP 3 - verify. Uses SHOW rather than information_schema, which
-- shared-hosting users cannot read (MySQL error #1044).
-- ---------------------------------------------------------------------------
-- Expect `perUnitAmount` as decimal(12,2), NULL allowed, no default.
SHOW COLUMNS FROM `ClientService` LIKE 'perUnitAmount';


-- ---------------------------------------------------------------------------
-- STEP 4 - optional. Read-only: lists rows the new rule has outgrown.
-- ---------------------------------------------------------------------------
-- Percentage rows on a service that is now package-only, and so should be
-- re-entered as a package amount or a per-count rate. EMPTY means nothing to
-- do. Nothing is changed here: the correct amount is a business decision, not
-- something this migration can compute.
SELECT c.`name` AS client, cs.`service`, cs.`percentage`
FROM `ClientService` cs
JOIN `Client` c ON c.`id` = cs.`clientId`
WHERE cs.`paymentType` = 'Percentage'
  AND cs.`service` <> 'Digital Marketing'
ORDER BY c.`name`, cs.`service`;
