-- Task -> Client / work mapping: adds Task.clientId + Task.clientWork.
--
-- DDL generated by Prisma, not hand-written:
--   npx prisma migrate diff --from-schema-datamodel <pre-change schema> \
--       --to-schema-datamodel prisma/schema.prisma --script
--
-- Run in phpMyAdmin (hPanel -> Databases -> Enter phpMyAdmin -> SQL tab)
-- against BOTH databases:
--   u230921990_office          (production, used by the live site)
--   u230921990_office_testing  (whatever local .env points at)
--
-- clientWork stores one of the parent client's services exactly as it appears
-- in Client.services, focus area included (e.g. "Digital Marketing (SEO)").
-- Both columns are nullable, so the 2 existing tasks stay valid as internal
-- tasks with no client mapping. No existing data is read or rewritten.


-- ---------------------------------------------------------------------------
-- STEP 1 - preflight. Run this first, on its own, and read the output.
-- ---------------------------------------------------------------------------
-- Expect one row named `Client`. If it returns EMPTY, stop and run
-- prisma/create-missing-tables.sql first: the foreign key in step 2 needs the
-- Client table to exist, and will fail with #1215 / #1005 without it.
SHOW TABLES LIKE 'Client';

-- Expect NO clientId / clientWork rows. If they are already listed, step 2 has
-- been applied to this database and must be skipped.
SHOW COLUMNS FROM `Task`;


-- ---------------------------------------------------------------------------
-- STEP 2 - the migration. Run only after step 1 looks as described above.
-- ---------------------------------------------------------------------------
-- MySQL has no "ADD COLUMN IF NOT EXISTS", so this is not re-runnable:
-- a second run fails with #1060 (duplicate column). That error is harmless and
-- simply means this database already has the change.

-- AlterTable
ALTER TABLE `Task` ADD COLUMN `clientId` VARCHAR(191) NULL,
    ADD COLUMN `clientWork` VARCHAR(191) NULL;

-- CreateIndex
CREATE INDEX `Task_clientId_fkey` ON `Task`(`clientId`);

-- AddForeignKey
-- SET NULL on delete: removing a client leaves its tasks in place, unmapped.
ALTER TABLE `Task` ADD CONSTRAINT `Task_clientId_fkey` FOREIGN KEY (`clientId`) REFERENCES `Client`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;


-- ---------------------------------------------------------------------------
-- STEP 3 - verify. Uses SHOW rather than information_schema, which
-- shared-hosting users cannot read (MySQL error #1044).
-- ---------------------------------------------------------------------------
-- Expect `clientId` and `clientWork` columns, the KEY `Task_clientId_fkey`,
-- and the CONSTRAINT `Task_clientId_fkey` REFERENCES `Client` (`id`).
SHOW CREATE TABLE `Task`;
